### PR TITLE
8991: use correct name for putSetting and add test for api-key persist failure

### LINKED ISSUE #8991: POST public-keys does not persist key when returning a successful response
## Describe the bug
The POST API keys function returns successfully, but does not persist the key 

## Impact on ReportStream
The new MVP UI for adding public keys can be worked on.

## Steps to reproduce
1. Add a key via the POST endpoint
2. Fetch the keys for the organization
3. Added key will not be included in the response

## Expected behavior
The key should be included in the response

## Resources
If applicable, add screenshots, links, etc to help explain your problem.

## Logs
If applicable, please attach logs to help describe your problem.

## Additional context
Add any other historical context about the problem here.

### PR DESCRIPTION
**Pull request by mkalish**
This PR fixes the bug where the api key is not persisted via the POST endpoint due to a typo in the `putSetting` call

Test Steps:
1. Add an api key
```sh
curl --location 'http://localhost:7071/api/settings/organizations/simple_report/public-keys?scope=simple_report.*.report&kid=simple_report' \
--header 'Authorization: Bearer dummy' \
--header 'Content-Type: text/plain' \
--data '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/iNl3p3b0G4a5AbhycX
0gnzszqSjMP7NJygno4UfF8HA+jLKqKXbG93ywyvbau+Rm1J7wbVb5hYWx3jvXt2
7LfQea1XgMF67O2Xo7bJ7U5NSceVVrtAA/IIq5sqolrxcVQ5LbGkuVqVTKwMtgs2
pe+sj6GcgdjhRnxLCN0Ex4xB7RtsieIvqwqEi4ds+sbLAs9fHMumcGzvyDLQpNGW
avOMqpXM1WqNauzOn4mgECu4BJuHPu7gXIPAkrVwLRF0LcSs7Js37uWtg04FxTz8
6sv0kYwqYXDJNcrCd+3S5cbQTGvdLAbUvvZ3vassfrxbQGFKJEt51iiHW7U/CaX8
ewIDAQAB
-----END PUBLIC KEY-----'
```
2. Verify the key was persisted
```sh
curl --location 'http://localhost:7071/api/settings/organizations/simple_report/public-keys' \
--header 'Authorization: Bearer dummy' 
``` 

## Changes
- Updates the POST public key function to invoke putSetting correctly
- Adds a new test that verifies when putSetting fails that the endpoint returns a BAD_REQUEST

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [x] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [x] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #8991

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

File: prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt [hunk 1]
```diff
@@ -85,15 +84,18 @@ class ApiKeysFunctions(private val settingsFacade: SettingsFacade = SettingsFaca
 
             val updatedKeys = JwkSet.addKeyToScope(organization.keys, scope, jwk)
 
-            settingsFacade.putSetting(
-                SettingType.ORGANIZATION.name,
+            val (result, error) = settingsFacade.putSetting(
+                organization.name,
```
Comment (mkalish) [inline prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt:88]: This was a typo from doing a refactor before merging, but was not caught do to how the mocking was setup in the tests

File: prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt [hunk 2]
```diff
@@ -373,6 +373,31 @@ class ApiKeysFunctionsTest {
             val response = ApiKeysFunctions().post(httpRequestMessage, organization.name)
             assertThat(response.status).isEqualTo(HttpStatus.UNAUTHORIZED)
         }
+
+        @Test
+        fun `Test returns the error if one is encountered persisting the key`() {
```
Comment (mkalish) [inline prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt:378]: Test covers the situation where the putSetting fails and confirms that the client sees the error

File: prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt [hunk 3]
```diff
@@ -95,11 +96,10 @@ class ApiKeysFunctionsTest {
         every { SettingsFacade.common } returns facade
         every {
             facade.putSetting<OrganizationAPI>(
-                any<String>(),
+                organization.name,
```
Comment (mkalish) [inline prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt:99]: Tightened this mock such that it also confirms the correct parameters are passed.

**Review by arnejduranovic — APPROVED** [review]
