### PR TITLE
Send retries over longer period of time.

### LINKED ISSUE #6797: Add a loooong-wait retry delay when Send fails.
We agreed at the Monday 9/19/2022 Dev Sync that we'd explore adding one or two more retries, with long delays, to our "exponential" backoff mechanism.  Note that the backoff mechanism is already in place.  This is just a case of adding to it.

See `SendFunction.kt`.  As of this writing, these are the retries:

```
// index is retryCount, value is in minutes
// We often send every 2 hours.   Idea here is that the 4th retry occurs *before* the next round of sends, in 111 mins.
val retryDuration = mapOf(1 to 1L, 2 to 5L, 3 to 30L, 4 to 75L, 5 to 120L)
```
(Note:  that comment looks mildly wrong: there's no real pattern to how often we send any more.   We send as often as every 10 mins, and as rare as once a day)

In addition we talked about a feature to "Hold All Sends".  However, we believe this can be done now by shutting down just the Send step.  Should experiment to prove this is true, in Staging.

See PR #7185

### PR DESCRIPTION
**Pull request by TomNUSDS**
### Changes
- Change times for existing send retries so they are more spread out (last retry is 24hrs).
- Fixed off-by-one bug uncovered while stepping through code. First retry has actually been `[2]` instead of `[1]` (FYI. Map is 1-based array)

@jimduff-usds _**Several issues turned up during testing. See the github comment history below as well as comments inline in the changed files**_

### Notes: 
 - There are NO major logic changes, just existing the times being updated and some bug fixes.
 - Because the retries are spread out more, the time until a send is considered "failed" is no much longer. Before it was ~4hr (231 minutes), now it's closer to 1d 17hr.
 - Increased "random dither" for time from +/-1 minute to +/- 5minutes. Not sure what a good rule of thumb is but it timeouts are 2 minutes, then a 1 minute dither seems too low. This means that after a failure the first retry time will be some random delay between 5-10 minutes. 

### Test Steps:
1. Break settings (e.g. bad password) so a sends break. (On localhost, you can just stop the docker services that act as receivers: `prime-router_rest-webservice_1`, `prime-router_sftp_1`, `prime-router_soap-webservice_1`... sends will fail)
2. Use Metabase (staging) or breakpoints (localhost) to watch failures/retries.

Fixes #6797

### CODE REVIEW

File: prime-router/src/main/kotlin/azure/SendFunction.kt [hunk 1]
```diff
@@ -29,14 +29,27 @@ import kotlin.random.Random
 /**
  * Azure Functions with HTTP Trigger. Write to blob.
  */
-const val dataRetentionDays = 7L
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/SendFunction.kt:32]: Unused removed

File: prime-router/src/main/kotlin/azure/SendFunction.kt [hunk 2]
```diff
@@ -29,14 +29,27 @@ import kotlin.random.Random
...
 const val send = "send"
-const val maxRetryCount = 4
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/SendFunction.kt:34]: This count should stay in sync with the size of the array. No idea why we didn't just use `retryDurationInMin.size - 1`? Fixed below, so removed constant.

File: prime-router/src/main/kotlin/azure/SendFunction.kt [hunk 3]
```diff
@@ -160,8 +173,8 @@ class SendFunction(private val workflowEngine: WorkflowEngine = WorkflowEngine()
                 ReportEvent(Event.EventAction.SEND_ERROR, reportId, isEmptyBatch)
             } else {
                 // retry using a back-off strategy
-                val waitMinutes = retryDuration.getOrDefault(nextRetryCount, maxDurationValue)
-                val randomSeconds = Random.nextInt(-30, 31)
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/SendFunction.kt:164]: Moved into constant since -30 could produce negative time if first retry is < 30s.

File: prime-router/src/main/kotlin/azure/SendFunction.kt [hunk 4]
```diff
@@ -29,14 +29,27 @@ import kotlin.random.Random
...
+// needed in case retry index is out-of-bounds call but should not be every be used
+const val defaultMaxDurationValue = 120L
+
+// exact time of next retry is slightly randomized to avoid the situation when
+// there's a system-wide failure and everything that's failed retries at the exact
+// same time producing a spike that makes things worse.
+// This is +/- around the actual retry, so they are spread out by up to 2x the value
+// It should always be > than the first entry of the retryDurationInMin above
+const val initialRetryInMin = 10
+const val ditherRetriesInSec = (initialRetryInMin / 2 * 60)
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/SendFunction.kt:42]: "dither" was hard coded to `Random.nextInt(-30, 31)` Moved into constant value and documented.

File: prime-router/src/main/kotlin/azure/Event.kt [hunk 5]
```diff
@@ -210,7 +210,7 @@ class ProcessEvent(
         return (7 * eventAction.hashCode()) +
             (31 * reportId.hashCode()) +
             (17 * at.hashCode()) +
-            (19 * retryDuration.hashCode())
+            (19 * retryDurationInMin.hashCode())
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/Event.kt:213]: Not clear what values were minutes vs seconds. Renamed

**Comment by TomNUSDS** [comment]
@jimduff-usds 
While testing this I found something odd with retries. It always starts with retry count = 2. Stepping through the code shows something odd with the `resendEvent()` and I could use another set of eyes. You seem to be the original author.

First issue is that `retryItems` is assigned a constant and then tested. I just want to make sure this is a simple bug (e.g. it since we reach this point it the code we know from the code above `retryItems` should be constant.

image

File: prime-router/src/main/kotlin/azure/Event.kt [hunk 6]
```diff
@@ -207,10 +207,11 @@ class ProcessEvent(
     }
 
     override fun hashCode(): Int {
+        // vars used in hashCode() must match those in equals()
         return (7 * eventAction.hashCode()) +
             (31 * reportId.hashCode()) +
             (17 * at.hashCode()) +
-            (19 * retryDuration.hashCode())
+            (19 * retryToken.hashCode())
```
Comment (TomNUSDS) [inline prime-router/src/main/kotlin/azure/Event.kt:214]: This just seems like a bug. hashCode() variables should match `equals()` and not contain a constant?

Note, this bug popped out when renaming the constant array `retryDuration` to `retryDurationInMin` ... which makes me wonder if `retryDurationMapInMin` isn't a better name?

File: prime-router/src/main/kotlin/azure/SendFunction.kt (hunk 1 above)
Comment (jimduff-usds) [reply prime-router/src/main/kotlin/azure/SendFunction.kt:32]: Yes, this is a leftover.   I believe this number has been moved to the react code.

File: prime-router/src/main/kotlin/azure/Event.kt (hunk 6 above)
Comment (jimduff-usds) [reply prime-router/src/main/kotlin/azure/Event.kt:214]: OK

File: prime-router/src/main/kotlin/azure/SendFunction.kt (hunk 2 above)
Comment (jimduff-usds) [reply prime-router/src/main/kotlin/azure/SendFunction.kt:34]: thanks

**Review by jimduff-usds — APPROVED** [review]
Thanks!

Let's give these numbers a try - warn O&O team when your PR goes live.

I'd love a follow-on where we pass in the retryDurationInMin map as an argument (or use injektion?), so we can write some smoke tests for retries without having to wait 1 day 17 hours and 10 minutes for the test to complete.

**Comment by oslynn** [comment]
Tested with my local host with stoping the prime-router_sftp_1 container
'==============================================
2023-03-09T00:41:14.209392317Z [2023-03-09T00:41:14.209Z] FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp
2023-03-09T00:41:14.209457477Z [2023-03-09T00:41:14.209Z] 00:41:14.208 [pool-2-thread-60][906] WARN  gov.cdc.prime.router.azure.SendFunction - Send Failed.  Will retry sending report: a71cd171-b63d-40d2-b19c-2c58894aeeb5 to md-phd.elr in 10 minutes and -13 seconds at 2023-03-09T00:51:01.208753Z
'======================
2023-03-09T00:51:00.999410784Z [2023-03-09T00:51:00.999Z] FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp
2023-03-09T00:51:00.999668920Z [2023-03-09T00:51:00.999Z] 00:51:00.999 [pool-2-thread-65][1304] WARN  gov.cdc.prime.router.azure.SendFunction - Send Failed.  Will retry sending report: a71cd171-b63d-40d2-b19c-2c58894aeeb5 to md-phd.elr in 60 minutes and -11 seconds at 2023-03-09T01:50:49.998855Z
'========================
2023-03-09T01:50:51.179896588Z [2023-03-09T01:50:51.179Z] FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp
2023-03-09T01:50:51.180358893Z [2023-03-09T01:50:51.180Z] 01:50:51.179 [pool-2-thread-73][1575] WARN  gov.cdc.prime.router.azure.SendFunction - Send Failed.  Will retry sending report: a71cd171-b63d-40d2-b19c-2c58894aeeb5 to md-phd.elr in 240 minutes and -282 seconds at 2023-03-09T05:46:09.179394Z
'=========================

2023-03-09T05:46:08.720046748Z [2023-03-09T05:46:08.719Z] FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp
2023-03-09T05:46:08.720401818Z [2023-03-09T05:46:08.720Z] 05:46:08.719 [pool-2-thread-124][3567] WARN  gov.cdc.prime.router.azure.SendFunction - Send Failed.  Will retry sending report: a71cd171-b63d-40d2-b19c-2c58894aeeb5 to md-phd.elr in 720 minutes and -94 seconds at 2023-03-09T17:44:34.719565Z
'===========================

2023-03-10T17:41:31.787880640Z [2023-03-10T17:41:31.787Z] FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp
2023-03-10T17:41:31.788115563Z [2023-03-10T17:41:31.787Z] 17:41:31.787 [pool-2-thread-554][21061] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId a71cd171-b63d-40d2-b19c-2c58894aeeb5 to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP) (orgService = md-phd.elr), Exception: sftp, All retries failed.  Manual Intervention Required.  Send Error report for: a71cd171-b63d-40d2-b19c-2c58894aeeb5 to md-phd.elr

**Comment by jimduff-usds** [comment]
Very minor note:   I think there was one more retry that occurred than shows in the logs above.    Total time is about 41 hours, which looks right.
