### PR TITLE
handle no data case for URL in Message Tracker

### LINKED ISSUE #8599: Message Tracker: Receiver table displays line-rule in some cells
## Describe the bug
Some cells display a thick line rule in empty cells. Other cells are empty entirely. We should handle empty cells by displaying `N/A` or `-` label. 

## Impact on ReportStream
Confusing and unclear interpretation of empty cells; creates inconsistency in how we handle certain states.

## Steps to reproduce
1. On Production, search for Message ID `29ba810a-b516-4a7f-aba3-4ec0fe89d834`
2. Click on the Message ID detail 
3. Scroll down to Receivers table

## Expected behavior
We should handle empty cells by displaying `N/A` or `-` label. 

## Logs
If applicable, please attach logs to help describe your problem.

#### Desktop (please complete the following information)
 - OS: iOS
 - Browser Google Chrome
 - Version 110.0.5481.177

## Additional context
Add any other historical context about the problem here.

### PR DESCRIPTION
**Pull request by etanb**
This PR ...

Fixes an issue in the Message Tracker table if the URL we're parsing has no data and returns an empty string.

Test Steps:

1. Go to latest version of ReportStream locally
2. Go to Message Search
3. Locally, go to a message with no data in the `receiverItem.fileUrl` OR just replace `formattedData.Main` to force the `N/A` string.

## Changes

Screenshot 2023-03-06 at 10 44 50 AM

_default state for N/A_

## Linked Issues
- Fixes #8599

### CODE REVIEW

**Review by jpandersen87 — APPROVED** [review]

File: frontend-react/src/components/MessageTracker/MessageReceivers.tsx [hunk 1]
```diff
@@ -74,6 +74,8 @@ const StatusEnum = {
     READY: "READY",
 };
 
+const noDataString = "N/A";
```
Comment (stephenkao) [inline frontend-react/src/components/MessageTracker/MessageReceivers.tsx:77]: MINOR POINT, but mind updating the variable name here to be something like `NO_DATA_STRING` instead?  Just signifying that it's a static value for the rest of the app lifetime

File: frontend-react/src/components/MessageTracker/MessageReceivers.tsx [hunk 2]
```diff
@@ -178,11 +180,14 @@ const MessageReceiversRow = ({
             <td className={getColumnClasses(ColumnDataEnum.Main)}>
                 <p
                     className={classnames(
-                        "font-mono-sm border-1px bg-primary-lighter radius-md padding-left-1 padding-right-1 margin-top-0",
+                        "font-mono-sm padding-left-1 padding-right-1 margin-top-0",
                         {
-                            "bg-blue-5": uppercaseMain === StatusEnum.BATCH,
-                            "bg-blue-10": uppercaseMain === StatusEnum.PROCESS,
-                            "bg-blue-20": uppercaseMain === StatusEnum.READY,
+                            "bg-blue-5 border-1px bg-primary-lighter radius-md":
```
Comment (stephenkao) [inline frontend-react/src/components/MessageTracker/MessageReceivers.tsx:185]: Not asking for this now, but it might be nice to split this out into like a StatusPill component or something.  Let's keep tabs on this and see if we'll actually use this motif elsewhere for now!

**Review by stephenkao — APPROVED** [review]
Looks good to me too!
