### PR TITLE
7578 fix deliveries API authorization

### LINKED ISSUE #7578: Delivery details unauthorized for receivers
## Problem statement

As a receiver on the ReportStream React app, I receive a 401 Unauthorized error when accessing Delivery Details from the Daily Data list page.

## Recreate

1. Login with _NO_ PrimeAdmin group, only a receiver group, on your Okta account
2. View Daily Data
3. Click through one of the IDs to the details page
4. You will get 3-4 401's as it retries the call on each failure until it hits its limit

## Expected behavior

- [ ] Endpoint validates the organization to see its own reports

## To do

- [ ] ...

### PR DESCRIPTION
**Pull request by jimduff-usds**
This PR creates parallel authorization code for the various Delivery and Submission endpoints by allowing both to authorize based on sending and/or receiving organization names in the ACTION table.

Prior, the Submissions API validated against the organization name in the ACTION table, and the Deliveries API authorization was broken for non PrimeAdmin users, due to missing receiver info in the ACTION table.

This PR fixes that.

## Test Steps:  How to test if the bug is fixed

With ReportStream running locally...

#### Generate some fake data destined for Maryland:
```
./prime data --input-fake 10 --target-states MD --input-schema primedatainput/pdi-covid-19 --output ./md.csv
```
#### Submit the fake data:
```
curl -X POST -H "client:simple_report.default" -H  "Content-Type: text/csv" --data-binary "@./md.csv" "http://localhost:7071/api/reports"
```
### OK, we have new data, now on to the test

At this point, the easier way to test is to run the UI locally, and login to the UI with a proletarian md-phd user, to see the Delivery details for the above newly submitted data.   If you do not have such a user, you cannot test this bug fix (Older data will still not work!)

Or, if you are an old school commandline person, and want to test the API directly, do these steps:

#### IMPORTANT:  Login as a lowly oktapreview user who can only access md-phd data.  Do NOT login as PrimeAdmin!
```
% ./prime login --env staging
About to launch a browser to log in to Okta...
Login valid until 2023-01-26T10:17:42.919664
```

#### Magic that puts the token into an env var, useful in your curl command.
```
% export TOK=$(cat ~/.prime/accesstoken.json | grep token | cut -d"," -f1 | cut -d":" -f2 | tr -d \")         
```
#### DELIVERY LIST QUERY - Use the "pageSize" param to grab the data you just submitted
```
curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "http://localhost:7071/api/waters/org/md-phd.elr/deliveries?pageSize=1"
```
#### DELIVERY DETAILS QUERY Replace the UUID in this below query with reportId UUID from the above query you just ran

**Finally!  This is the query that was broken and is now fixed.**

```
curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "http://localhost:7071/api/waters/report/a39b9d99-dc4b-4547-987e-c9436b47d345/delivery"
```

If you like you can try the facilities flavor of this too:
```
curl -H "authentication-type: okta" -H "Authorization: Bearer $TOK" "http://localhost:7071/api/waters/report/a39b9d99-dc4b-4547-987e-c9436b47d345/facilities"
```

Note that these queries will ONLY work on newly submitted and processed reports.  Older data will still return
`{"error": "Unauthorized"}`

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

### Testing
- [X] Tested locally?
- [X] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [N] Are there licensing issues with any new dependencies introduced?
- [X] Includes a summary of what a code reviewer should test/verify?
- [N/A ] Updated the release notes?
- [No] Database changes are submitted as a separate PR?
- [N/A] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #7578

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

### CODE REVIEW

File: prime-router/src/main/kotlin/azure/ActionHistory.kt [hunk 1]
```diff
@@ -312,6 +312,18 @@ class ActionHistory(
...
+     * Typically, this would be called when a report is batched for that receiver, sent to that receiver,
+     * downloaded by that receiver, or any other action taken by that receiver or on behalf of that receiver.
+     * @param organizationName  The name of the receiving organization to associate with this action.
+     * @param receiverName  The name of the receiver channel to associate with this action.
+     */
+    fun trackActionReceiverInfo(organizationName: String, receiverName: String) {
+        action.receivingOrg = organizationName
+        action.receivingOrgSvc = receiverName
+    }
+
```
Comment (jimduff-usds) [inline prime-router/src/main/kotlin/azure/ActionHistory.kt:326]: This is the meat of the change:  addition of columns to the Action table that let us track the receivingOrg.

This already exists for the sendingOrg side, so we are just adding it for the receivingOrg, so that our receiving and sending history APIs can have parallel code.

You could make a strong case that these various Org/Sender/Receiver string values should always have been in the Action table, and not the Report_file table, because putting these values in the action table lets us track info for error cases, when no report_file entry is created.

File: prime-router/src/main/kotlin/azure/BatchFunction.kt [hunk 2]
```diff
@@ -68,6 +68,7 @@ class BatchFunction(
         try {
             val receiver = workflowEngine.settings.findReceiver(event.receiverName)
                 ?: error("Internal Error: receiver name ${event.receiverName}")
+            actionHistory.trackActionReceiverInfo(receiver.organizationName, receiver.name)
```
Comment (jimduff-usds) [inline prime-router/src/main/kotlin/azure/BatchFunction.kt:71]: When we batch, keep track of who its going to.

File: prime-router/src/main/kotlin/azure/HistoryFunctions.kt [hunk 3]
```diff
@@ -343,6 +343,7 @@ open class BaseHistoryFunction : Logging {
 
                 val actionHistory = ActionHistory(TaskAction.download)
                 actionHistory.trackActionRequestResponse(request, response)
+                actionHistory.trackActionReceiverInfo(header.reportFile.receivingOrg, header.reportFile.receivingOrgSvc)
```
Comment (jimduff-usds) [inline prime-router/src/main/kotlin/azure/HistoryFunctions.kt:346]: when we Download, keep track of which org is downloading.

File: prime-router/src/main/kotlin/azure/SendFunction.kt [hunk 4]
```diff
@@ -68,6 +68,7 @@ class SendFunction(private val workflowEngine: WorkflowEngine = WorkflowEngine()
             workflowEngine.handleReportEvent(event) { header, retryToken, _ ->
                 val receiver = header.receiver
                     ?: error("Internal Error: could not find ${header.task.receiverName}")
+                actionHistory.trackActionReceiverInfo(receiver.organizationName, receiver.name)
```
Comment (jimduff-usds) [inline prime-router/src/main/kotlin/azure/SendFunction.kt:71]: when we send, keep track of which org its sent to.

File: prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt [hunk 5]
```diff
@@ -104,19 +105,17 @@ class DeliveryFacade(
...
-        orgName: String?,
-        senderOrReceiver: String?,
+        action: Action,
         request: HttpRequestMessage<String?>,
     ): Boolean {
-        // todo If orgname is not known, this only works for primeadmin right now.
-        //  Need to query the report_file table to find who the receiving_org is for this id.
-        return claims.authorizedForSendOrReceive(orgName, null, request)
+        return claims.authorizedForSendOrReceive(action.receivingOrg, null, request)
     }
```
Comment (jimduff-usds) [inline prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt:119]: This is the key line here - its checking for a match of the action.receivingOrg.

**Comment by jimduff-usds** [comment]
fyi I found an unrelated issue with a full-elr smoke test while testing this.  See #8294

**Comment by arnejduranovic** [comment]
> login to the UI with a proletarian md-phd user

How can I create such a user? Or are there shared creds we use? Change looks good to me but did not test it yet due to missing creds.

**Review by thetaurean — APPROVED** [review]
Looks good! Learned a lot from reviewing the test changes.

This doesn't need to wait on my changes, it will be a clean rebase on my end.
