### PR TITLE
Experience/6341: return Valid status if warnings but no errors are submitted

### LINKED ISSUE #6341: Validate endpoint returns 400 when only warnings are returned
**Describe the bug**
When submitting a file to the `/api/validate` endpoint that only returns warnings (but no errors), a 400 Bad Request status is returned. When submitting that _same_ file to the `/api/waters` endpoint, a 200 OK or 201 Created status is returned. Since the `validate` endpoint is supposed to effectively behave exactly like the `waters` endpoint (minus the logging, db-writing and sending), this results in a confusing inconsistency.

**Impact**
Impact is minimal for the time being, since the only consumer of the endpoint is the Validate page of the web app, which is currently hidden behind a feature flag. However, even that page currently works around the inconsistency, and is not adversely affected. The impact will be greater when/if the service becomes consumable by external consumers who come to depend on that return status.

**To Reproduce**
1. Log into RS as prime admin
2. Make sure the "validation-service" feature flag is set
3. Set your org and choose "Validate" from the "Upload & Validate" menu
4. Open up your browser's web tools and go to the Network tab
5. Upload your sample HL7 or CSV file that only throws warnings (not errors)
6. Observe that the "validate" network call returns a 400, when it should be 200

Alternatively, contrast and compare API calls to `validate` and `waters` in PostMan or curl

**Expected behavior**
A 200 http status should be returned when only warnings are returned

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sethdarragile6**
This PR returns Valid status (http 201) if warnings but no errors are submitted to the `/api/validate` endpoint. This makes the endpoint's behavior more consistent with the actual file submission endpoint  (`/api/waters`).

Test Steps:
1. Log into RS as prime admin
2. Make sure the "validation-service" feature flag is set
3. Set your org and choose "Validate" from the "Upload & Validate" menu
4. Open up your browser's web tools and go to the Network tab
5. Upload your sample HL7 or CSV file that only throws warnings (not errors)
6. Observe that the "validate" network call now returns a 201 in the Network tab, indicating a Valid status

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #6341 
- Relates to #5713 and #6285

### CODE REVIEW

**Review by ahay-agile6 — APPROVED** [review]

File: prime-router/src/main/kotlin/azure/ValidateFunction.kt [hunk 1]
```diff
@@ -125,8 +125,8 @@ class ValidateFunction(
                         payloadName
                     )
 
-                    // return CREATED status, report submission was successful
-                    HttpStatus.CREATED
+                    // return OK status, report validation was successful
+                    HttpStatus.OK
                 } else HttpStatus.OK
```
Comment (clediggins-usds) [inline prime-router/src/main/kotlin/azure/ValidateFunction.kt:130]: Why is there an if/else here? both result in HttpStatus.OK. Is the if/else still even valid?  Do the options CheckConnections and ValidatePayload even make sense?  I'd say no, since this *is* the validation endpoint.

Probably just get rid of the if/else entirely. Run the validateAndMoveToProcessing for validation, and then return HttpStatus.OK if it isn't kicked out with an exception by the validateAndMoveToProcessing function

**Review by clediggins-usds — CHANGES_REQUESTED** [review]

File: prime-router/src/main/kotlin/azure/ValidateFunction.kt (hunk 1 above)
Comment (sethdarragile6) [reply prime-router/src/main/kotlin/azure/ValidateFunction.kt]: @clediggins-usds good call, I've removed it.

**Review by clediggins-usds — APPROVED** [review]
