### PR TITLE
Fix overflow during integer parse of constants

### LINKED ISSUE #12609: Bug: Integer parsing exception during constant resolution
## Describe the bug
We attempt to stick all strings consisting of only digits into an `IntegerType` which can throw an exception if the numbers is too large (or too small).

## Steps to reproduce
1. Run the unit test `test fhir path resolver multiple values` with a string field consisting of only numbers greater than `Integer.MAX`

## Expected behavior
Attempt to parse a strings of only digits into an integer but fallback to a string if an exception is thrown.

## Logs
```
Exception while executing function: Functions.translate-fhir Result: Failure
Exception: NumberFormatException: For input string: "6000352053"
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor1013.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
	at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
	at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: ca-order-observations in CA-receiver-transform to FHIR bundle. 
Error was: Error encountered while applying: ca-specimen in ca-order-observation to FHIR bundle. 
Error was: Error encountered while applying: ca-specimen-organization-identifier in ca-specimen to FHIR bundle. 
Error was: Error encountered while applying: organization-identifier in ../../../common/organization-identifier to FHIR bundle. 
Error was: java.lang.NumberFormatException: For input string: "6000352053"
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:123)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema$default(FhirToHl7Converter.kt:101)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.convert(FhirToHl7Converter.kt:91)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.getHL7MessageFromBundle$prime_router(FHIRTranslator.kt:188)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.getByteArrayFromBundle$prime_router(FHIRTranslator.kt:164)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.doWork(FHIRTranslator.kt:75)
	at gov.cdc.prime.router.fhirengine.engine.FHIREngine.run(FHIREngine.kt:173)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:150)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:149)
	at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning$lambda$1(DatabaseAccess.kt:106)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:531)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6068)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at org.jooq.impl.Tools$3.get(Tools.java:6065)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
	at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning(DatabaseAccess.kt:106)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.runFhirEngine(FHIRFunctions.kt:149)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate(FHIRFunctions.kt:129)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate$default(FHIRFunctions.kt:123)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.translate(FHIRFunctions.kt:114)
	... 17 more
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: ca-specimen in ca-order-observation to FHIR bundle. 
Error was: Error encountered while applying: ca-specimen-organization-identifier in ca-specimen to FHIR bundle. 
Error was: Error encountered while applying: organization-identifier in ../../../common/organization-identifier to FHIR bundle. 
Error was: java.lang.NumberFormatException: For input string: "6000352053"
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:123)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processElement$prime_router(FhirToHl7Converter.kt:170)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:121)
	... 38 more
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: ca-specimen-organization-identifier in ca-specimen to FHIR bundle. 
Error was: Error encountered while applying: organization-identifier in ../../../common/organization-identifier to FHIR bundle. 
Error was: java.lang.NumberFormatException: For input string: "6000352053"
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:123)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processElement$prime_router(FhirToHl7Converter.kt:170)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:121)
	... 40 more
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: organization-identifier in ../../../common/organization-identifier to FHIR bundle. 
Error was: java.lang.NumberFormatException: For input string: "6000352053"
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:123)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processElement$prime_router(FhirToHl7Converter.kt:170)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:121)
	... 42 more
Caused by: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: "6000352053"
	at org.hl7.fhir.r4.model.IntegerType.parse(IntegerType.java:90)
	at org.hl7.fhir.r4.model.IntegerType.parse(IntegerType.java:39)
	at org.hl7.fhir.r4.model.PrimitiveType.fromStringValue(PrimitiveType.java:108)
	at org.hl7.fhir.r4.model.PrimitiveType.setValueAsString(PrimitiveType.java:164)
	at org.hl7.fhir.r4.model.IntegerType.<init>(IntegerType.java:66)
	at gov.cdc.prime.router.fhirengine.translation.hl7.utils.FhirPathCustomResolver.resolveConstant(ConstantResolver.kt:167)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.resolveConstant(FHIRPathEngine.java:1729)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.resolveConstant(FHIRPathEngine.java:1625)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1476)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:664)
	at gov.cdc.prime.router.fhirengine.translation.hl7.utils.FhirPathUtils.evaluateString(FhirPathUtils.kt:166)
	at gov.cdc.prime.router.fhirengine.translation.hl7.ConfigSchemaProcessor.getValueAsString$prime_router(ConfigSchemaProcessor.kt:34)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processElement$prime_router(FhirToHl7Converter.kt:181)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:121)
	... 44 more
Caused by: java.lang.NumberFormatException: For input string: "6000352053"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.hl7.fhir.r4.model.IntegerType.parse(IntegerType.java:88)
	... 57 more
```

### PR DESCRIPTION
**Pull request by thetaurean**
This PR stops an attempted integer cast that is resulting in an overflow error in production.

Test Steps:
1. Run tests

## Changes
- Do not cast values to Integer in `ConstantResolver.kt`
  - Adjust related tests to expect String

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] ~~Added~~ Modified tests?

## Linked Issues
- Fixes #12609

## To Be Done
- Decide what the path forward is (will we try again to cast? maybe fallback to string?)

### CODE REVIEW

File: prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt [hunk 1]
```diff
@@ -161,14 +158,8 @@ class FhirPathCustomResolver(private val customFhirFunctions: FhirPathFunctions?
...
-                // Convert string constants that are whole integers to Integer type to facilitate math operations
-                values.map {
-                    if (it is StringType && StringUtils.isNumeric(it.primitiveValue())) {
-                        IntegerType(it.primitiveValue())
-                    } else {
-                        it
-                    }
-                }
+                // previously we cast numbers to integers; see https://github.com/CDCgov/prime-reportstream/issues/12609
+                values
```
Comment (jalbinson) [inline prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt:162]: We should use try/catch logic on the initial integer parsing code so that numbers that can be parsed as integers still are. This will avoid downstream effects if we do happen to be doing some sort of math operation.

File: prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt [hunk 2]
```diff
@@ -164,7 +164,11 @@ class FhirPathCustomResolver(private val customFhirFunctions: FhirPathFunctions?
                 // Convert string constants that are whole integers to Integer type to facilitate math operations
                 values.map {
                     if (it is StringType && StringUtils.isNumeric(it.primitiveValue())) {
-                        IntegerType(it.primitiveValue())
+                        try {
+                            IntegerType(it.primitiveValue())
+                        } catch (e: NumberFormatException) {
+                            it // fallback to string; see https://github.com/CDCgov/prime-reportstream/issues/12609
```
Comment (jalbinson) [inline prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt:170]: Add an extra field in the existing unit test: [test fhir path resolver multiple values](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt#L138)

Make the extra field something that triggers the catch block to ensure it falls back to a string.
```kotlin
val bigNumberString = "999999999999999999999999"
```

Comment (thetaurean) [reply prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt]: I added a test and adjusted the catch clause to handle the correct exception type (`IllegalArgumentException`) as well as rethrow if the `.cause` is not a `NumberFormatException`.

**Review by jalbinson — APPROVED** [review]
looks good!

**Review by arnejduranovic — APPROVED** [review]
Looks good! Jamie created a follow up ticket to update the fix for a more long term solution here: https://github.com/CDCgov/prime-reportstream/issues/12625
