### PR TITLE
Experience-8602: Add FHIR format to list of options

### LINKED ISSUE #8602: Dropdown in sender UI is missing "FHIR" as a data format option.
## Describe the bug
This dropdown needs to also include "FHIR" as a valid format:

Note:  its possible there's an error in the backend as well.  I've had trouble saving changes to this data associated with a sender whose  data format is "FHIR".

## Impact on ReportStream

Can't make changes to data whose format is "FHIR".

## Steps to reproduce

I definitely saw this is staging.    Not sure if you'll see it locally, but here goes:

Load ./settings/staging/0149-etor.yml into your local settings (see instructions at the top of that file)

Then run the UI locally and attempt to make changes to setting flexion.etor-service-sender.

## Expected behavior

FHIR is an allowed data type, both in the dropdown and the back end.

### PR DESCRIPTION
**Pull request by stephenkao**
Pretty simple change!  Just adding FHIR as an available format in addition to CSV and HL7.  This'll allow us to update Sender formats through the admin Organization settings view.

Test Steps:
1. Log in as an admin
2. Go to the Organization settings page
3. Choose an Organization with a Sender service and click 'Edit'
4. Click the Format dropdown --> ensure that `FHIR` shows up as an option and that it can be saved as such

## Changes
Screenshot 2023-03-06 at 10 14 46

### Testing
- [x] Tested locally?
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?</strike>
- [x] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
<strike>- [ ] Added tests?</strike>

## Linked Issues
- Fixes #8602

### CODE REVIEW

File: frontend-react/src/hooks/UseFileHandler.ts [hunk 1]
```diff
@@ -11,6 +11,7 @@ export enum ErrorType {
     FILE = "file",
 }
 
+// TODO: consolidate with Format in TemporarySettingsAPITypes.ts
```
Comment (stephenkao) [inline frontend-react/src/hooks/UseFileHandler.ts:14]: Will add a ticket for this -- should be pretty simple, but I'd rather break it out into a separate change so as to not adversely affect the validator logic.

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by jpandersen87 — APPROVED** [review]

File: frontend-react/src/hooks/UseFileHandler.ts (hunk 1 above)
Comment (stephenkao) [reply frontend-react/src/hooks/UseFileHandler.ts:14]: https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8606
