### PR TITLE
Address intermediate "Not Delivering" before routing a received report

### LINKED ISSUE #15524: [BUG]: History endpoint intermediate overallStatus can be "Not Delivering" and then change later
## Describe the bug
`end2end_up` tests were failing during deployment when run against the staging environment because the history endpoint that the tests rely on were not showing that the tests were delivered where we expected them to be. In fact, in one case, the history endpoint showed an overall status of "Not Delivering" when a query of the customEvents showed the reports was correctly delivered. Manually hitting the history endpoint later showed expected results: overallStatus was "delivered" and the receivers were correct. 

TLDR; It seems like "not delivering" can sometimes be an "intermediary" result whereas it should be a final result. Meaning if a report is marked as "not delivering", then its status should not change at some later point in time.

## Impact on ReportStream
Senders, if using the history endpoint, may not get accurate information as to the real status of their submitted report and may lead to confusion.

## Steps to reproduce
Hard to reproduce since it relies on the processing speed of the report. It may be easier to comb through overallStatus calculation logic and identify the defect that way.

## Expected behavior
- "Not Delivering" should not be an intermediary status, only a final one.
- Create test that reproduces this issue

### LINKED ISSUE #15645: [BUG] Submission History API doesn't show Filtered reports
## Describe the bug
When filters are triggered for receivers they do not show up when calling Submission History API `{{url}}/waters/report/{reportId}/history`. The submission status says `Waiting to Deliver` and should say `Failed to Deliver` and under destinations filteredReports should be populated.

## Impact on ReportStream

Senders, if using the history endpoint, may not get accurate information as to the real status of their submitted report and may lead to confusion.

Engagement team uses API to troubleshoot submission and ensure filters are working as expected.

## Steps to reproduce
Send a report locally and make sure the submission triggers a qualityFilter. You can do this by updating a receiver's quality filter to false:`qualityFilter: ["false"]`
Call the Submission History API  `{{url}}/waters/report/2558/history`

It seems like the new steps added to the Universal Pipeline are breaking this API. The API was probably looking at the Action Log Route step records to return this information.

## Expected behavior
- "Failed to deliver" should be the status that is displayed when a report fails quality filters.
- Destinations object should return filters triggered.

### PR DESCRIPTION
**Pull request by thetaurean**
This PR adjusts submission history calculation logic to take into account next actions that are not scheduled for any particular time (that only use `nextAction` and don't set a `nextActionAt`).

Test Steps:
1. Run tests

## Changes
- SubmissionHistory
  - Adds logic to submission history to check nextAction as well as nextActionAt
  - Fixes bug in submission history logic to find last action
- Test and test utility changes
  - Adds a submission history integration test for a received & converted report
  - Adds logic to `ReportGraphBuilder`/`ReportNodeBuilder`to set `createdAt` to avoid same value for all nodes
  - Adds logic to `ReportGraphBuilder`/`ReportNodeBuilder` to explicity set `nextAction`
  - Sets `nextAction` to `none` for tests cases where reports will not be delivered

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] Added tests?

## Linked Issues
- Fixes #15524 
- Fixes #15645

### CODE REVIEW

**Review by adegolier — COMMENTED** [review]
Ran new test against master and it failed, passes against this branch, so 👍 there

File: prime-router/src/main/kotlin/history/SubmissionHistory.kt [hunk 1]
```diff
@@ -182,6 +182,12 @@ class DetailedSubmissionHistory(
     @JsonIgnore
     var nextActionScheduled = false
 
+    /**
+     * Flag to check if there's a next action for the newest report in this submission
+     */
+    @JsonIgnore
+    var hasNextAction = false
```
[the remark this answers is not in the document]
Comment (thetaurean) [reply prime-router/src/main/kotlin/history/SubmissionHistory.kt:189]: `nextActionScheduled` tracks scheduled next actions -- ones that use the `nextActionAt` field. Currently that's only the send step (maybe batch also but I don't think so).

`hasNextAction` tracks `nextAction`, looking at the latest report in the lineage.

File: prime-router/src/test/kotlin/common/ReportNodeBuilder.kt [hunk 2]
```diff
@@ -130,7 +142,14 @@ class ReportGraphBuilder {
...
             .setTransportResult(node.theTransportResult)
-            .setNextAction(node.reportGraphNodes.firstOrNull()?.theAction)
+            .setNextAction(
+                if (node.theNextAction != null) {
+                    node.theNextAction
+                } else {
+                    node.reportGraphNodes.firstOrNull()?.theAction
+                }
+            )
+            .setCreatedAt(graph.node.createdAt.plusMinutes(1))
```
Comment (thetaurean) [inline prime-router/src/test/kotlin/common/ReportNodeBuilder.kt:152]: This was added because the nodes were generating with the same timestamp. This caused a sorting algorithm in the submission history function to fail which prevented it from finding the correct last action/report in the lineage.

File: prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
Comment (thetaurean) [inline prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt:1]: This adds a couple more assertions for #15846

**Review by adegolier — APPROVED** [review]
lgtm

**Review by arnejduranovic — APPROVED** [review]
